# your domain
domain: proxypool-8ty.cloud.okteto.net
port:  12580

# source list file
source-files:
  # use local file
  - /proxypool-src/conf/proxypool/source.yaml
  # use web file
  # - https://example.com/config/source.yaml

# ======= 可选项，留空使用default值  =======

# postgresql database info
database_url: ""

# interval between each crawling
crawl-interval: 70      # v0.5.x default 60 (minutes)
crontime:             # v0.4.x default 60 (minutes). Deprecated in the newest version

healthcheck-timeout:        # default 5 (seconds)
healthcheck-connection:     # default 500. The number of health check connections simultaneously


# speed test
speedtest: true         # default false. Warning: this will consume large network resources.
speedtest-interval: 20  # default 720 (min)
connection: 20          # default 5. The number of speed test connections simultaneously
timeout: 10              # default 10 (seconds).
## active proxy speed test
active-interval: 15     # default 60 (min)
active-frequency: 5    # default 100 (requests per interval)
active-max-number: 1000   # default 100. If more than this number of active proxies, the extra will be deprecated by speed

# cloudflare api
cf_email: ""
cf_key: ""
